[versions]
android = "7.4.2"
androidxTestRunner = "1.5.2"
binaryCompat = "0.13.0"
configuration = "0.1.0-beta02"
endians = "0.1.0"
gradleVersions = "0.46.0"
kotlin = "1.8.10"
publish = "0.24.0"

[libraries]
kotlincrypto-endians-endians = { module = "org.kotlincrypto.endians:endians", version.ref = "endians" }
gradle-kmp-configuration = { module = "io.matthewnelson:gradle-kmp-configuration-plugin", version.ref = "configuration" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }

# Tests
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
binaryCompat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompat" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
